#!MC 1100

$!PICK SETMOUSEMODE
  MOUSEMODE = SELECT
$!EXTRACTFROMPOLYLINE 
  EXTRACTTHROUGHVOLUME = NO
  EXTRACTLINEPOINTSONLY = NO
  INCLUDEDISTANCEVAR = NO
  NUMPTS = 100
  EXTRACTTOFILE = YES
  FNAME = 'D:\Temp\ramp_p.dat' 
  RAWDATA
2
0.1 0 2
0.1 2 2
$!PICK SETMOUSEMODE
  MOUSEMODE = SELECT

