#!MC 1410
$!VarSet |MFBD| = 'R:\Cavity_April_2018\Slices'
$!WRITEDATASET  "R:\Cavity_April_2018\M219_Lip\M219_Lip_200000.dat"
  INCLUDETEXT = NO
  INCLUDEDATASHARELINKAGE = YES
  ZONELIST =  [702]
  VARPOSITIONLIST =  [1,4-6]
  BINARY = NO
  USEPOINTFORMAT = YES
  PRECISION = 9
  TECPLOTVERSIONTOWRITE = TECPLOTCURRENT
$!RemoveVar |MFBD|
