#!MC 1400
$!FILECONFIG
LOADONDEMAND
{
	UNLOADSTRATEGY = MINIMIZEMEMORYUSE
}
$!Loop |NumZones|
	LOADONDEMAND
	{
		UNLOADSTRATEGY = MINIMIZEMEMORYUSE
	}
	$!CREATEFEBOUNDARY
	SOURCEZONE = |Loop|
$!EndLoop