#!MC 1410
$!VarSet |MFBD| = 'U:\Priyam\pipe\pipe_all_files'
$!EXPORTSETUP EXPORTFORMAT = JPEG
$!EXPORTSETUP EXPORTREGION = ALLFRAMES
$!EXPORTSETUP IMAGEWIDTH = 2000
$!EXPORTSETUP QUALITY = 100
$!EXPORTSETUP EXPORTFNAME = 'U:\Priyam\pipe\pipe_all_files\real_vs_imag.jpeg'
$!EXPORT 
  EXPORTREGION = ALLFRAMES
$!RemoveVar |MFBD|
